In [17]:
import pytesseract
from pytesseract import Output
import csv
import pandas as pd
pytesseract.pytesseract.tesseract_cmd = "C:\\Program Files\\Tesseract-OCR\\tesseract.exe"
import cv2
import numpy as np
from matplotlib import pyplot as plt
img = cv2.imread('1.JPG')
height, width, channel = img.shape

def imshow(img, label='default'):
    cv2.imshow(label, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [18]:
img = cv2.resize(img, (width*2, height*2))

In [19]:
imshow(img)

In [20]:
alpha = 0.9
beta = 0
adjusted = cv2.convertScaleAbs(img, alpha=alpha, beta=beta)
adjusted = cv2.resize(adjusted, (width*2, height * 2))

# display the output image
imshow(adjusted)


In [21]:
height, width, channel = img.shape
# img = cv2.resize(img, (width*2, height*2))

# Convert image to grey scale
gray_image = cv2.cvtColor(adjusted, cv2.COLOR_BGR2GRAY)
#gray_image = cv2.resize(gray_image, (width*2, height * 2))
# Converting grey image to binary image by Thresholding
#thresh_img = cv2.threshold(gray_image, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)[1]
#ret2,th2 = cv2.threshold(img,0,255,cv2.THRESH_BINARY | cv2.THRESH_OTSU)

imshow(gray_image)


In [23]:
thresh_img = cv2.threshold(gray_image, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)[1]
imshow(thresh_img)


In [24]:
canny = cv2.Canny(img, 0, 150, apertureSize = 5)
imshow(canny)

In [26]:
gray_image = cv2.cvtColor(adjusted, cv2.COLOR_BGR2GRAY)
thresh_img = cv2.threshold(gray_image, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)[1]

imshow(gray_image)
kernel = np.ones((1,30), np.uint8)  #for horizontal erosion
e_im = cv2.erode(gray_image, kernel, iterations=2)  #performing erosion
imshow(e_im)



edges = cv2.Canny(e_im,0,150,apertureSize = 5)     #edges

minLineLength=333
#houghlines for detecting those erosion lines
lines = cv2.HoughLinesP(image=edges,rho=0.5,theta=np.pi/180, threshold=222,lines=np.array([]), minLineLength=minLineLength,maxLineGap=7) 
a,b,c = lines.shape
# Draw the lines
if lines is not None:
    for i in range(0, len(lines)):
        l = lines[i][0]
        cv2.line(thresh_img, (l[0], l[1]), (l[2], l[3]), (0, 0, 255), 3, cv2.LINE_AA)

imshow(thresh_img)



In [31]:
kernel = np.ones((500,12), np.uint8)  #for horizontal erosion
e_im = cv2.erode(gray_image, kernel, iterations=4)  #performing erosion
imshow(e_im)

edges = cv2.Canny(e_im,100,0,apertureSize = 3)
#imshow(edges)


lines = cv2.HoughLinesP(image=edges,rho=0.5,theta=np.pi/180, threshold=222,lines=np.array([]), minLineLength=minLineLength,maxLineGap=7) 
a,b,c = lines.shape
# Draw the lines
if lines is not None:
    for i in range(0, len(lines)):
        l = lines[i][0]
        cv2.line(thresh_img, (l[0], l[1]), (l[2], l[3]), (0, 0, 255), 3, cv2.LINE_AA)

imshow(thresh_img)

In [36]:
imshow(thresh_img)





In [145]:


output_text = []
test = []
custom_config = r'-l eng --oem 3 --psm 4 -c tessedit_char_whitelist="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-:.$%./@& *"'


# Get all OCR output information from pytesseract
ocr_output_details = pytesseract.image_to_data(thresh_img, output_type = Output.DICT, config=custom_config, lang='eng')
# Total bounding boxes
n_boxes = len(ocr_output_details['text'])

# Extract and draw rectangles for all bounding boxes
for i in range(n_boxes):
    (x, y, w, h) = (ocr_output_details['left'][i], ocr_output_details['top'][i], ocr_output_details['width'][i], ocr_output_details['height'][i])
    cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)

# Print OCR Output
print(ocr_output_details.keys())

# Arrange output text from OCR into the format as per image

word_list = []
last_word = []

for word in ocr_output_details['text']:
    # If there is no text in an element
    if word != '':
        word_list.append(word)
        last_word = word
    # Append final list of words with valid words
    if (last_word != '' and word == '') or (word == ocr_output_details['text'][-1]):
        output_text.append(word_list)
        test.append(word_list)
        word_list = []


dict_keys(['level', 'page_num', 'block_num', 'par_num', 'line_num', 'word_num', 'left', 'top', 'width', 'height', 'conf', 'text'])


In [37]:
line_counter = 0
for line in output_text:
    if line:
        print(line)
        
        for idx, word in enumerate(line):
            print(idx,word)
            print(line_counter)
            #created postions meta
            #get check line
            if check:
                
                while not word in check[line_counter]:
                    line_counter+=1
                else:
                    fetched_pos = check[line_counter].find(word)
                    if fetched_pos < 0:
                        print(f"Couldn't find word")
                    elif fetched_pos < 17:
                        row = 1
                    elif fetched_pos < 33:
                        row = 2
                    elif fetched_pos < 52:
                        row = 2
                    elif fetched_pos < 67:
                        row = 2
                    elif fetched_pos < 18:
                        row = 2
                    print(f"{word} is in row {row}")
                      
    
                        
                    
                    
                    
                    
                    
                    
            else:
                line_counter+= 1
            
            
            break
        break

NameError: name 'output_text' is not defined

In [148]:
check = list(text.split("\n"))
print(check[1])

print(pos)


      Nikhil     Honda Cars      Manager Project    IT              nikhilarora@hondacarindia.com J 9811745280 
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [151]:
check

['',
 '      Nikhil     Honda Cars      Manager Project    IT              nikhilarora@hondacarindia.com J 9811745280 ',
 '  Arora          India Ltd       Manager IT ',
 '  &  Anil        New  Holland    Manager Deputy     IT              anil.patnaik@cnh.com            9999898176 ',
 '  Patnaik        Fiat            Manager                                                            / 9109134400 ',
 '  @&  Mr.        Paytm           vP                 Information     priyank.nag@paytmbank.com       9810566462 ',
 '  Priyank Nag    Payment Bank                       Technology ',
 '  @   Pankaj     GFL Ltd.        GM  GM             IT              pshrivastava@gfl.co.in          012 ',
 '     .                           Information                                                        06149600 ',
 '  Shrivastava ',
 '                                 Technology                                                         Ext:966 ',
 '  &  Aftab       Mahagun         Manager            IT 

In [152]:
x = check[1]
len(x)

print(x)
z = [y for y in range(len(x))]
print(z)

      Nikhil     Honda Cars      Manager Project    IT              nikhilarora@hondacarindia.com J 9811745280 
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110]


In [154]:
col1_pos = x.find('Honda')
col2_pos = x.find('Manager')
col1_pos

17

In [156]:

col2_pos

33

In [157]:
col3_pos = x.find('IT')
col3_pos

52

In [158]:
col4_pos = x.find('nikh')
col4_pos

68

In [160]:
col5_pos = x.find('9811745280')
col5_pos

100

In [112]:
check_line = [x for x in output_text1]
check_line

[[],
 [],
 [],
 [],
 [' Nischal',
  'Tv',
  'Today',
  'Manager',
  'Information',
  'nischal.maheshwari@intoday.com',
  '9818444340'],
 ['Maheshwari', 'Network', 'Technology'],
 [],
 ['@',
  'Sandeep',
  'Zee',
  'Media',
  'Manager',
  'Information',
  'sandeep.mishra@zeemedia.esselgroup.com',
  '9811417694'],
 ['Mishra', 'Limited.', 'Technology'],
 [],
 ['@', 'Prashant', 'Manager', 'IT', 'prashant.bhardwaj@flexfilm.com', '0'],
 ['Bhardwaj', 'Manager', '-', 'IT', '9873912930'],
 ['Ravi',
  'Uflex',
  'GM',
  'Sr',
  'GM',
  'IT',
  'ravi.ramakrishnan@flexfilm.com',
  '9891001443'],
 ['Ramakrishnan', 'Global-IT']]

In [73]:
output_text

[[],
 [],
 [],
 [],
 ['Tv',
  'Today',
  'Manager',
  'Information',
  'nischal.maheshwari@intoday.com',
  '9818444340'],
 ['Network', 'Technology'],
 [],
 [],
 [' Nischal'],
 ['Maheshwari'],
 [],
 [],
 ['@',
  'Sandeep',
  'Zee',
  'Media',
  'Manager',
  'Information',
  'sandeep.mishra@zeemedia.esselgroup.com',
  '9811417694'],
 [],
 [],
 ['Mishra', 'Limited.', 'Technology'],
 [],
 [],
 ['Amit', 'Roy', 'GM', 'DGN-IT', 'royamitak@rediffmail.com', '9971747321'],
 [],
 [],
 ['@', 'Prashant', 'Manager', 'prashant.bhardwaj@flexfilm.com', '0'],
 ['Manager', '-', 'IT', '9873912930'],
 [],
 [],
 ['Bhardwaj'],
 [],
 [],
 ['Ravi', 'GM', 'Sr', 'GM', 'ravi.ramakrishnan@flexfilm.com', '9891001443'],
 ['Ramakrishnan', 'Global-IT'],
 [],
 [],
 []]

In [72]:
#--psm 6
for pos, check_line in enumerate(output_text1):
    print(check_line)
    for idx


[]
[]
[]
[]
[' Nischal', 'Tv', 'Today', 'Manager', 'Information', 'nischal.maheshwari@intoday.com', '9818444340']
['Maheshwari', 'Network', 'Technology']
[]
['@', 'Sandeep', 'Zee', 'Media', 'Manager', 'Information', 'sandeep.mishra@zeemedia.esselgroup.com', '9811417694']
['Mishra', 'Limited.', 'Technology']
[]
['@', 'Prashant', 'Manager', 'IT', 'prashant.bhardwaj@flexfilm.com', '0']
['Bhardwaj', 'Manager', '-', 'IT', '9873912930']
['Ravi', 'Uflex', 'GM', 'Sr', 'GM', 'IT', 'ravi.ramakrishnan@flexfilm.com', '9891001443']
['Ramakrishnan', 'Global-IT']


In [70]:
check_line

[]

In [146]:





custom_config = r'-l eng --oem 3 --psm 6 -c tessedit_char_whitelist="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-:.$%./@& *"'
d = pytesseract.image_to_data(thresh_img, config=custom_config, output_type=Output.DICT)
df = pd.DataFrame(d)

# clean up blanks
df1 = df[(df.conf != '-1') & (df.text != ' ') & (df.text != '')]
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# sort blocks vertically
sorted_blocks = df1.groupby('block_num').first().sort_values('top').index.tolist()
for block in sorted_blocks:
    curr = df1[df1['block_num'] == block]
    sel = curr[curr.text.str.len() > 3]
    # sel = curr
    char_w = (sel.width / sel.text.str.len()).mean()
    prev_par, prev_line, prev_left = 0, 0, 0
    text = ''
    for ix, ln in curr.iterrows():
        
        # add new line when necessary
        if prev_par != ln['par_num']:
            text += '\n'
            prev_par = ln['par_num']
            prev_line = ln['line_num']
            prev_left = 0
        elif prev_line != ln['line_num']:
            text += '\n'
            prev_line = ln['line_num']
            prev_left = 0

        added = 0  # num of spaces that should be added
        if ln['left'] / char_w > prev_left + 1:
            added = int((ln['left']) / char_w) - prev_left
            text += ' ' * added
        text += ln['text'] + ' '
        prev_left += len(ln['text']) + added + 1
        
    text += '\n'
    print(text)
   


      Nikhil     Honda Cars      Manager Project    IT              nikhilarora@hondacarindia.com J 9811745280 
  Arora          India Ltd       Manager IT 
  &  Anil        New  Holland    Manager Deputy     IT              anil.patnaik@cnh.com            9999898176 
  Patnaik        Fiat            Manager                                                            / 9109134400 
  @&  Mr.        Paytm           vP                 Information     priyank.nag@paytmbank.com       9810566462 
  Priyank Nag    Payment Bank                       Technology 
  @   Pankaj     GFL Ltd.        GM  GM             IT              pshrivastava@gfl.co.in          012 
     .                           Information                                                        06149600 
  Shrivastava 
                                 Technology                                                         Ext:966 
  &  Aftab       Mahagun         Manager            IT              aahmad@mahagunindia.com         9

In [75]:
text

'\n   Nischal       Tv Today        Manager            Information    nischal.maheshwari@intoday.com           9818444340 \n  Maheshwari     Network                            Technology \n  @  Sandeep     Zee Media       Manager            Information    sandeep.mishra@zeemedia.esselgroup.com   9811417694 \n  Mishra         Limited.                           Technology \n  @  Prashant                    Manager            IT             prashant.bhardwaj@flexfilm.com           0 \n  Bhardwaj                       Manager - IT                                                               9873912930 \n  Ravi           Uflex           GM  Sr GM          IT             ravi.ramakrishnan@flexfilm.com           9891001443 \n  Ramakrishnan                   Global-IT \n'

In [80]:
check = list(text.split("\n"))
check[1]

'   Nischal       Tv Today        Manager            Information    nischal.maheshwari@intoday.com           9818444340 '

[[ 206 1049  206    0]]
[[1388 1046 1388    0]]
[[ 226 1049  226    0]]
[[ 446 1049  446    0]]
[[ 946 1049  946    0]]
[[ 912 1049  912    0]]
[[ 703 1049  703    0]]
[[  13 1049   13    0]]
[[ 452 1049  452    0]]
[[ 722 1049  722    0]]
[[1393 1049 1393    0]]
